/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Punktestand: typeof import('./src/components/Punktestand.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teilnehmer: typeof import('./src/components/Teilnehmer.vue')['default']
    Zeitplan: typeof import('./src/components/Zeitplan.vue')['default']
  }
}
