name: Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Push docs folder
      run: |
        git config --global user.email "beagleplays@gmail.com"
        git config --global user.name "beagleplays"
        git checkout develop
        git add docs
        git commit -m "Add built docs"
        git push https://beagleplays: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@github.com/beagleplays/eldenlordchallenge.git develop 
